### ISSUE TITLE
Standalone devtools broken after v6.3.0

### ISSUE THREAD

**Issue by Uninen** [vuejs/devtools-v6#1952]
### Version
6.4.1

### Browser and OS info
Firefox 104 / macOS 12.6

### Steps to reproduce
1. yarn add -D @vue/devtools@6.2.1
2. ./node_modules/.bin/vue-devtools
3. Open http://localhost:8098/  --> works ok

then

1. yarn add -D @vue/devtools@6.4.1
2. ./node_modules/.bin/vue-devtools
3. Open http://localhost:8098/  --> error

```
Error: ENOENT: no such file or directory, open '/Users/uninen/Code/Misc/devtoolstest/node_modules/@vue/devtools/build/hook.js'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
    at /Users/uninen/Code/Misc/devtoolstest/node_modules/@vue/devtools/server.js:17:26
    at Layer.handle [as handle_request] (/Users/uninen/Code/Misc/devtoolstest/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/uninen/Code/Misc/devtoolstest/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/uninen/Code/Misc/devtoolstest/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/uninen/Code/Misc/devtoolstest/node_modules/express/lib/router/layer.js:95:5)
    at /Users/uninen/Code/Misc/devtoolstest/node_modules/express/lib/router/index.js:284:15

```

### What is expected?
Working devtools in standalone mode

### What is actually happening?
Error with stacktrace like above.

---
Version 6.2.1 works ok, version 6.3.0 up to 6.4.1 produce the error above.

**Comment by Akryum** [comment]
I don't know why some folders are suddenly not included in npm publish, they must have changed something... :(
